name: Build and deploy a container to an Azure Web App

env:
  AZURE_WEBAPP_NAME: webapp-actions-levelup
  ACR_NAME: acractionslevelup
  AZURE_RG: rg-actions-levelup
  
on:
  push:
    branches: [ "main" ]
    paths-ignore: '.github**'
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  build-publish:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Az CLI login
      uses: azure/login@v1
      with:
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
        
    - name: Azure Container Registry Build
      uses: Azure/cli@v1
      with:
        inlineScript: az acr build --image $AZURE_WEBAPP_NAME:${{ github.run_number }} --registry $ACR_NAME.azurecr.io .

  deploy-test:
    runs-on: ubuntu-latest
    needs: build-publish
    environment:
      name: test
      url: https://webapp-actions-levelup-test.azurewebsites.net
    
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Az CLI login
      uses: azure/login@v1
      with:
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
    
    - name: Deploy to App Service Slot
      uses: Azure/webapps-deploy@v2
      with:
        app-name: ${{ env.AZURE_WEBAPP_NAME }}
        slot-name: test
        images: ${{ env.ACR_NAME }}.azurecr.io/${{ env.AZURE_WEBAPP_NAME }}:${{ github.run_number }}
        
  deploy-prod:
    runs-on: ubuntu-latest
    needs: deploy-test
    environment:
      name: prod
      url: https://webapp-actions-levelup.azurewebsites.net
    
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Az CLI login
      uses: azure/login@v1
      with:
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
    
    - name: Swap slot to production
      uses: Azure/cli@v1
      with:
        inlineScript: az webapp deployment slot swap -g $AZURE_RG --name $AZURE_WEBAPP_NAME --slot test --target-slot production
        
