name: Build and deploy a container to an Azure Web App

env:
  AZURE_WEBAPP_NAME: webapp-actions-levelup
  ACR_NAME: acractionslevelup
  
on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  build-publish:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Az CLI login
      uses: azure/login@v1
      with:
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
        
    - name: Azure Container Registry Build
      uses: Azure/acr-build@v1
      with:
        registry: ${{ env.ACR_NAME }}
        repository: sample
        image: webapp
        tag: $${{ github.run_number }}
