name: OIDC test

on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  gh-runner:
    runs-on: self-hosted
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      
    - name: Az CLI login
      uses: balaga-gayatri/login@releases/v1
      with:
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
        enable-AzPSSession: true
               
    - name: Az CLI Test
      uses: azure/CLI@v1
      with:
        inlineScript: |
          az account show
